// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDyfuWAVHwegGnlL1-gMiEhZvPPZd9b1as',
    appId: '1:589188122280:web:04b7d6ed0378eead85649d',
    messagingSenderId: '589188122280',
    projectId: 'fir-auth-v1-tuba',
    authDomain: 'fir-auth-v1-tuba.firebaseapp.com',
    storageBucket: 'fir-auth-v1-tuba.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCoudWVdhFriXxELiC7eo_cKnJqImTLweM',
    appId: '1:589188122280:android:1e7133a974044e2185649d',
    messagingSenderId: '589188122280',
    projectId: 'fir-auth-v1-tuba',
    storageBucket: 'fir-auth-v1-tuba.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCEIr_T8Sikm1UClYmvmp5Zm1c9ZnXepFs',
    appId: '1:589188122280:ios:a1096c8fc2ded98785649d',
    messagingSenderId: '589188122280',
    projectId: 'fir-auth-v1-tuba',
    storageBucket: 'fir-auth-v1-tuba.appspot.com',
    iosBundleId: 'com.example.stateChangeDemo',
  );

}